### ISSUE TITLE
Renaming the package

### ISSUE THREAD

**Issue by BenjaminBorn** [lucabrugnolini/VAR#3]
Hi Luca,

It's kind of unfortunate that the package and the module have different names: `VAR` vs `VARs`. I think the Julia convention is to keep them the same. We cannot rename the module to `VAR` as that clashes with the function and type `VAR`. But what about naming the package and module `VectorAutoregressions.jl`. The name is a bit more descriptive for non-macroeconomists which might also help when registering the package. I also think it's not too long to type once in a `using` statement.

Let me know what you think. Best,

Benjamin

**Comment by lucabrugnolini** [comment]
I notice it yesterday while working out the example. I was thinking about
VARs.jl, but I like your suggestion. Thanks

Il gio 5 lug 2018, 10:41 Benjamin Born <notifications@github.com> ha
scritto:
